#  ██╗███╗   ██╗██████╗ ██╗   ██╗████████╗
#  ██║████╗  ██║██╔══██╗██║   ██║╚══██╔══╝
#  ██║██╔██╗ ██║██████╔╝██║   ██║   ██║
#  ██║██║╚██╗██║██╔═══╝ ██║   ██║   ██║
#  ██║██║ ╚████║██║     ╚██████╔╝   ██║
#  ╚═╝╚═╝  ╚═══╝╚═╝      ╚═════╝    ╚═╝
# ----------------------------------------

input {
    kb_layout = us,ru,id,jp

    kb_variant = ,,,kana

    kb_options = grp:alt_shift_toggle

    numlock_by_default = true

    repeat_rate = 50
    repeat_delay = 250

    follow_mouse = 1

    sensitivity = 0

    touchpad {
        natural_scroll = false

        scroll_factor = 0.8
    }
}

# optional

# gestures {
#     workspace_swipe = true
# 
#     workspace_swipe_fingers = 3
# 
#     workspace_swipe_distance = 400
# }

# Per-device

device {
    name = epic-mouse-v1
    sensitivity = 0
}
