# ██╗   ██╗ █████╗ ██████╗ ██╗ █████╗ ██████╗ ██╗     ███████╗███████╗
# ██║   ██║██╔══██╗██╔══██╗██║██╔══██╗██╔══██╗██║     ██╔════╝██╔════╝
# ██║   ██║███████║██████╔╝██║███████║██████╔╝██║     █████╗  ███████╗
# ╚██╗ ██╔╝██╔══██║██╔══██╗██║██╔══██║██╔══██╗██║     ██╔══╝  ╚════██║
#  ╚████╔╝ ██║  ██║██║  ██║██║██║  ██║██████╔╝███████╗███████╗███████║
#   ╚═══╝  ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝╚═════╝ ╚══════╝╚══════╝╚══════╝

$mod = SUPER 
$bin = ${XDG_BIN_HOME:-$HOME/bin}
$terminalRunner = kitty -e

# applications

$terminal = kitty
$terminalFm = kitty -e yazi

$fileManager = nemo

$menu = rofi -show drun
$rofimoji = rofimoji --selector rofi --selector-args='-theme ~/.config/rofi/themes/emoji.rasi' --hidden-descriptions

# browser

$browser = zen-browser

# editors

$editor = zeditor
$editorCli = nvim

# system

$lock = hyprlock

$logout = hyprctl dispatch exit

$shutdown = loginctl poweroff
$reboot = loginctl reboot

$suspend = loginctl suspend && hyprlock
$lockscreen = hyprlock

# file tools

$archive = file-roller


# media

$music = spotify

$video = mpv
$image = imv

# network

$wifi = nm-connection-editor

$bluetooth = blueman-manager

# utilities

$calculator = qalculate-qt

$notes = obsidian

$systemMonitor = kitty -e btop

$keybinds = cat ~/.config/hypr/keybinds_ui.txt | rofi -dmenu -i -theme ~/.config/rofi/themes/keybinds.rasi -p "󰌌 Keybinds"

# screenshots

$screenshot = flameshot gui

$record = wf-recorder

# clipboard

$clipboard = cliphist list | rofi -dmenu -i -theme ~/.config/rofi/themes/clipboard.rasi -p "󰅍 Clipboard" | cliphist decode | wl-copy
$clipboardcl = cliphist wipe && notify-send "Clipboard" "History cleared"

# power menu

$powermenu = wlogout
