# =========================================================
# HYPRIDLE
# minimal • clean • media-aware
# =========================================================

general {
    # lockscreen
    lock_cmd = pidof hyprlock || hyprlock

    # lock before suspend
    before_sleep_cmd = loginctl lock-session

    # wake displays after resume
    after_sleep_cmd = wlopm --on '*'

    # respect media / fullscreen inhibitors
    ignore_dbus_inhibit = false
}

# =========================================================
# DIM SCREEN
# =========================================================

listener {
    timeout = 180

    # save current brightness then dim
    on-timeout = brightnessctl -s set 10%

    # restore brightness
    on-resume = brightnessctl -r
}

# =========================================================
# LOCKSCREEN
# =========================================================

listener {
    timeout = 420

    on-timeout = loginctl lock-session
}

# =========================================================
# DISPLAY OFF
# =========================================================

listener {
    timeout = 600

    # turn displays off
    on-timeout = wlopm --off '*'

    # wake displays
    on-resume = wlopm --on '*'
}

# =========================================================
# SAFE SUSPEND
# =========================================================

listener {
    timeout = 1800

    on-timeout = ~/.local/bin/safe-suspend
}
