# ██╗  ██╗██╗   ██╗██████╗ ██████╗ ██╗      █████╗ ███╗   ██╗██████╗
# ██║  ██║╚██╗ ██╔╝██╔══██╗██╔══██╗██║     ██╔══██╗████╗  ██║██╔══██╗
# ███████║ ╚████╔╝ ██████╔╝██████╔╝██║     ███████║██╔██╗ ██║██║  ██║
# ██╔══██║  ╚██╔╝  ██╔═══╝ ██╔══██╗██║     ██╔══██║██║╚██╗██║██║  ██║
# ██║  ██║   ██║   ██║     ██║  ██║███████╗██║  ██║██║ ╚████║██████╔╝
# ╚═╝  ╚═╝   ╚═╝   ╚═╝     ╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝  ╚═══╝╚═════╝
# -------------------------------------------------------------------

# █▀▀ █▀▀▄ ▀█░█▀ ░▀░ █▀▀█ █▀▀█ █▀▀▄ █▀▄▀█ █▀▀ █▀▀▄ ▀▀█▀▀ 
# █▀▀ █░░█ ░█▄█░ ▀█▀ █▄▄▀ █░░█ █░░█ █░▀░█ █▀▀ █░░█ ░░█░░ 
# ▀▀▀ ▀░░▀ ░░▀░░ ▀▀▀ ▀░▀▀ ▀▀▀▀ ▀░░▀ ▀░░░▀ ▀▀▀ ▀░░▀ ░░▀░░
# See https://wiki.hyprland.org/Configuring/Environment-variables/

# Hyprland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland

# █▀▀ █▀▀█ █░░█ █▀▀█ █▀▀ █▀▀ 
# ▀▀█ █░░█ █░░█ █▄▄▀ █░░ █▀▀ 
# ▀▀▀ ▀▀▀▀ ░▀▀▀ ▀░▀▀ ▀▀▀ ▀▀▀

source = $HOME/.config/hypr/configs/variables.conf
source = $HOME/.config/hypr/configs/env.conf
source = $HOME/.config/hypr/configs/monitors.conf
source = $HOME/.config/hypr/configs/input.conf
source = $HOME/.config/hypr/configs/layout.conf
source = $HOME/.config/hypr/configs/appearance.conf
source = $HOME/.config/hypr/configs/rules.conf
source = $HOME/.config/hypr/configs/keybindings.conf
source = $HOME/.config/hypr/configs/autostart.conf
source = $HOME/.config/hypr/configs/misc.conf


# source = $HOME/.config/hypr/userprefs.conf
